---
  local:
    hosts:
      localhost:
        ansible_connection: local
  elasticsearch:
    hosts:
      elastic:
        ansible_connection: docker
  kibana:
    hosts:
      kibana:
        ansible_connection: docker
  logstash:
    hosts:
      logstash:
        ansible_connection: docker
